In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Project/AIProject/Augmented Images/Augmented Images',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 8120 files belonging to 6 classes.


In [ ]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Project/AIProject/Augmented Images/Augmented Images',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 8120 files belonging to 6 classes.


In [ ]:
cnn = tf.keras.models.Sequential()

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=128,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=256,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
cnn.add(tf.keras.layers.Conv2D(filters=512,kernel_size=3,activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

In [ ]:
cnn.add(tf.keras.layers.Dropout(0.25))

In [ ]:
cnn.add(tf.keras.layers.Flatten())

In [ ]:
cnn.add(tf.keras.layers.Dense(units=1500,activation='relu'))

In [ ]:
cnn.add(tf.keras.layers.Dropout(0.4))

In [ ]:
cnn.add(tf.keras.layers.Dense(units=6,activation='softmax'))

In [ ]:
cnn.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2  (None, 63, 63, 32)        0         
 D)                                                              
                                                                 
 conv2d_2 (Conv2D)           (None, 63, 63, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 30, 30, 64)        0         
 g2D)                                                   

In [ ]:
training_history = cnn.fit(x=training_set, validation_data=validation_set, epochs=5)

Epoch 1/5
254/254 [==============================] - 1579s 6s/step - loss: 0.7324 - accuracy: 0.7089 - val_loss: 0.2241 - val_accuracy: 0.9219
Epoch 2/5
254/254 [==============================] - 1274s 5s/step - loss: 0.1388 - accuracy: 0.9549 - val_loss: 0.0439 - val_accuracy: 0.9871
Epoch 3/5
254/254 [==============================] - 1252s 5s/step - loss: 0.0612 - accuracy: 0.9805 - val_loss: 0.0278 - val_accuracy: 0.9904
Epoch 4/5
254/254 [==============================] - 1298s 5s/step - loss: 0.0378 - accuracy: 0.9885 - val_loss: 0.0239 - val_accuracy: 0.9927
Epoch 5/5
254/254 [==============================] - 1295s 5s/step - loss: 0.0636 - accuracy: 0.9803 - val_loss: 0.0128 - val_accuracy: 0.9967


In [ ]:
train_loss, train_acc = cnn.evaluate(training_set)
print('Training accuracy:', train_acc)

254/254 [==============================] - 293s 1s/step - loss: 0.0128 - accuracy: 0.9967
Training accuracy: 0.9966748952865601


In [ ]:
val_loss, val_acc = cnn.evaluate(validation_set)
print('Validation accuracy:', val_acc)

254/254 [==============================] - 286s 1s/step - loss: 0.0128 - accuracy: 0.9967
Validation accuracy: 0.9966748952865601


In [ ]:
cnn.save('trained_plant_model.keras')

In [ ]:
training_history.history

{'loss': [0.732375979423523,
  0.1388382911682129,
  0.061203133314847946,
  0.0377674475312233,
  0.06358664482831955],
 'accuracy': [0.7088670134544373,
  0.9549261331558228,
  0.9805418848991394,
  0.9885467886924744,
  0.9802955389022827],
 'val_loss': [0.22406399250030518,
  0.04388408735394478,
  0.027820048853754997,
  0.023878980427980423,
  0.012830188497900963],
 'val_accuracy': [0.9219211935997009,
  0.9870689511299133,
  0.990394115447998,
  0.9927340149879456,
  0.9966748952865601]}

{'loss': [0.732375979423523,
  0.1388382911682129,
  0.061203133314847946,
  0.0377674475312233,
  0.06358664482831955],
 'accuracy': [0.7088670134544373,
  0.9549261331558228,
  0.9805418848991394,
  0.9885467886924744,
  0.9802955389022827],
 'val_loss': [0.22406399250030518,
  0.04388408735394478,
  0.027820048853754997,
  0.023878980427980423,
  0.012830188497900963],
 'val_accuracy': [0.9219211935997009,
  0.9870689511299133,
  0.990394115447998,
  0.9927340149879456,
  0.9966748952865601]}

In [ ]:
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

In [ ]:
print(training_history.history.keys())

In [ ]:
class_name = validation_set.class_names

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Project/AIProject/Test',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 33 files belonging to 1 classes.


In [ ]:
y_pred = cnn.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

33/33 [==============================] - 1s 12ms/step


In [ ]:
y_pred

array([[[[232.75, 229.75, 220.75],
         [228.25, 225.25, 216.25],
         [232.  , 229.  , 220.  ],
         ...,
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ]],

        [[231.5 , 228.5 , 219.5 ],
         [229.5 , 226.5 , 217.5 ],
         [232.  , 229.  , 220.  ],
         ...,
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ]],

        [[227.  , 224.  , 215.  ],
         [228.75, 225.75, 216.75],
         [228.75, 225.75, 216.75],
         ...,
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ],
         [254.  , 255.  , 247.  ]],

        ...,

        [[210.75, 207.75, 198.75],
         [214.5 , 211.5 , 202.5 ],
         [212.5 , 209.5 , 200.5 ],
         ...,
         [249.25, 246.25, 239.25],
         [249.  , 246.  , 239.  ],
         [247.5 , 244.5 , 237.5 ]],

        [[211.  , 208.  , 199.  ],
         [214.25, 211.25, 202.25],
         [21

In [ ]:
y_pred.shape

(33, 128, 128, 3)

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

<tf.Tensor: shape=(33,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])>

In [ ]:
Y_true.shape

TensorShape([33])

In [ ]:
predicted_categories

<tf.Tensor: shape=(33, 128, 3), dtype=int64, numpy=
array([[[ 0,  0,  0],
        [ 3,  3,  3],
        [ 0,  0,  0],
        ...,
        [19,  0,  0],
        [19,  0,  0],
        [19,  0,  0]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        ...,
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0, 12],
        [ 0,  0, 12],
        [ 0,  0, 12],
        ...,
        [ 0,  0,  4],
        [ 4,  0,  4],
        [ 0,  0, 10]],

       ...,

       [[90, 72, 92],
        [72, 72, 92],
        [75, 78, 92],
        ...,
        [ 4, 20, 28],
        [ 0, 20, 28],
        [ 0, 19, 28]],

       [[14, 14, 14],
        [14, 14, 14],
        [14, 14, 14],
        ...,
        [ 0, 21, 21],
        [ 0, 21, 21],
        [ 0, 21, 21]],

       [[ 7,  0,  0],
        [ 7,  0,  0],
        [ 7,  0,  0],
        ...,
        [ 0,  0,  4],
        [ 0,  0,  4],
        [ 0,  0,  0]]])>

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
plt.figure(figsize=(40, 40))
sns.heatmap(cm,annot=True,annot_kws={"size": 10})

plt.xlabel('Predicted Class',fontsize = 20)
plt.ylabel('Actual Class',fontsize = 20)
plt.title('Plant Disease Prediction Confusion Matrix',fontsize = 25)
plt.show()